### ISSUE TITLE
Click area of personal page left side bar (fixed? assess in progress)

### ISSUE THREAD

**Issue by ryanwooa** [UOA-CS732-SE750-Students-2024/project-group-noble-narwhals#15]
![image](https://github.com/UOA-CS732-SE750-Students-2024/project-group-noble-narwhals/assets/119087910/549ce4c9-bf24-4cd4-b297-64667e319b99)
I found that only the red area in the image can click. If you click the green area, there is no reaction. 
I think the green area should be clickable too. Please fix it.

@jlmjkfd 
@tpan501

**Comment by tpan501** [comment]
I will take a look today

**Comment by tpan501** [comment]
``` JS
      <Link to={to} className={`p-3 pl-4 flex items-center justify-start hover:bg-secondary text-white cursor-pointer ${activeClass} transition-colors duration-100 w-full`}  onClick={() => handleClick(label)}>
        {icon}
        {label}
      </Link>
```
This code should be okay to fix this bug please check
